Vagrant.configure(2) do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
  end

  config.vm.box = "bento/ubuntu-16.04"

  config.vm.network "private_network", ip: "10.61.6.31"
  config.vm.hostname = "7ml7w-minikanren"

  config.vm.synced_folder ".", "/vagrant"

  config.vm.provision "shell", path: "provision.sh"
end
